In [4]:
import pandas as pd
a=pd.read_excel("1.xlsx",sheet_name='Sheet1')  
a

,SL No,Timestamp,What is your name ?,Your Aadhar Card number,What is your age?,Are you traveling abroad ?,"If yes , give your passport number below.",Doses completed,dose type,"If yes, then when was the first dose of Vaccination?",...,Enter Gmail ID for slot updates,Unnamed: 13,Covin ID,Reg. Date,Unnamed: 16,Sheduled Date,Time,Unnamed: 19,Unnamed: 20,Unnamed: 21
0,AGSB0F0016,2021/05/27 9:55:26 PM GMT+5:30,Sriradha Kamath,229068412945,Below 45,No,NaN,Not done any,NaN,NaN,...,shantushenoy@gmail.com,NaN,7.730161e+13,NaN,NaN,NaN,NaN,NaN,vivek,ans
1,AGSB0F0001,2021/05/27 8:57:54 PM GMT+5:30,Karthik kamath,2329 1866 8808,Below 45,No,NaN,Not done any,NaN,NaN,...,karthikamath632@gmail.com,NaN,2.042942e+13,NaN,NaN,NaN,NaN,NaN,shreesha,answered
2,AGSB0F0002,2021/05/27 9:13:09 PM GMT+5:30,Hariprasad nayak,9451 9134 6890,Below 45,No,NaN,Not done any,NaN,NaN,...,karthikamath632@gmail.com,NaN,2.632201e+13,NaN,NaN,NaN,NaN,NaN,shreesha,answered
3,AGSB0F0003,2021/05/27 9:14:03 PM GMT+5:30,Nayana Kamath,6833 0465 3894,Below 45,No,NaN,Not done any,NaN,NaN,...,karthikamath632@gmail.com,NaN,9.277917e+13,NaN,NaN,NaN,NaN,NaN,shreesha,answered
4,AGSB0F0004,2021/05/27 9:30:27 PM GMT+5:30,Sakshi kamath,383583263417,Below 45,No,NaN,Not done any,NaN,NaN,...,sakzbkamath@gmail.com,NaN,8.370309e+13,NaN,NaN,NaN,NaN,NaN,vivek,ans
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
454,NaN,2021/05/29 11:59:58 AM GMT+5:30,Suvith S Nayak,962588902047,Below 18,No,NaN,Not done any,NaN,NaN,...,suvithnayak@gmail.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
455,NaN,2021/05/29 12:01:56 PM GMT+5:30,B Rajesh Pai,902927251577,Below 45,No,NaN,Not done any,NaN,NaN,...,pairb1979@gmail.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
456,NaN,2021/05/29 12:03:43 PM GMT+5:30,Rashmi R Pai,858335333693,Below 45,No,NaN,Not done any,NaN,NaN,...,pairb1979@outlook.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
457,NaN,2021/05/29 12:06:53 PM GMT+5:30,Girish. Kudva,639284505051,Below 45,No,NaN,Not done any,NaN,NaN,...,Girishkudva37@gmail.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
458,NaN,2021/05/29 12:10:52 PM GMT+5:30,Raghavendra Kini,620700302735,Below 45,No,NaN,Not done any,NaN,NaN,...,ragz79k@gmail.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
b=pd.read_excel("1.xlsx",sheet_name='Sheet2')  
b.count()

What is your name ?                                     50
Your Aadhar Card number                                 50
What is your age?                                       50
Are you traveling abroad ?                              49
If yes , give your passport number below.               11
Doses completed                                         50
dose type                                                0
If yes, then when was the first dose of Vaccination?     7
Mobile number                                           50
Gender                                                  50
Enter Gmail ID for slot updates                          0
Unnamed: 11                                              0
Covin ID                                                 0
Unnamed: 13                                              0
Sheduled Date                                            0
Time                                                     0
dtype: int64

In [30]:
a.merge(b, left_on='Timestamp', right_on='What is your name ?')
a.to_excel("Results.xlsx", index = False)

In [31]:
f1 = pd.read_excel("Results.xlsx")
f2 = pd.read_excel("2.xlsx")
f2=f2.drop_duplicates(subset=['Your Aadhar Card number'])
f1=f1.drop_duplicates(subset=['Your Aadhar Card number'])

In [32]:
f1.merge(f2,left_on='Timestamp',right_on='Timestamp1')
f1.to_excel("Results2.xlsx", index = False)

In [33]:
f1.count()

SL No                                                    20
Timestamp                                               402
What is your name ?                                     402
Your Aadhar Card number                                 402
What is your age?                                       402
Are you traveling abroad ?                              395
If yes , give your passport number below.                70
Doses completed                                         402
dose type                                                 1
If yes, then when was the first dose of Vaccination?     66
Mobile number                                           402
Gender                                                  399
Enter Gmail ID for slot updates                         136
Unnamed: 13                                               0
Covin ID                                                 73
Reg. Date                                                 0
Unnamed: 16                                               0
Sheduled Date                                             0
Time                                                     21
Unnamed: 19                                              33
Unnamed: 20                                              64
Unnamed: 21                                              62
dtype: int64